; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jan 13 2021 00:35:02 GMT-0600 (Central Standard Time)
; ================================================================================

DATA9WL3YBYKQV:
	dc.w $0, DATA9WL3YBYKQV_1-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_2-DATA9WL3YBYKQV, DATA9WL3YBYKQV_3-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_4-DATA9WL3YBYKQV, DATA9WL3YBYKQV_5-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_6-DATA9WL3YBYKQV, DATA9WL3YBYKQV_7-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_8-DATA9WL3YBYKQV, DATA9WL3YBYKQV_9-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_10-DATA9WL3YBYKQV, DATA9WL3YBYKQV_11-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_12-DATA9WL3YBYKQV, DATA9WL3YBYKQV_13-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_14-DATA9WL3YBYKQV, DATA9WL3YBYKQV_15-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_16-DATA9WL3YBYKQV, DATA9WL3YBYKQV_17-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_18-DATA9WL3YBYKQV, DATA9WL3YBYKQV_19-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_1A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_1B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_1C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_1D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_1E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_1F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_20-DATA9WL3YBYKQV, DATA9WL3YBYKQV_21-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_22-DATA9WL3YBYKQV, DATA9WL3YBYKQV_23-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_24-DATA9WL3YBYKQV, DATA9WL3YBYKQV_25-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_26-DATA9WL3YBYKQV, DATA9WL3YBYKQV_27-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_28-DATA9WL3YBYKQV, DATA9WL3YBYKQV_29-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_2A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_2B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_2C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_2D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_2E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_2F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_30-DATA9WL3YBYKQV, DATA9WL3YBYKQV_31-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_32-DATA9WL3YBYKQV, DATA9WL3YBYKQV_33-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_34-DATA9WL3YBYKQV, DATA9WL3YBYKQV_35-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_36-DATA9WL3YBYKQV, DATA9WL3YBYKQV_37-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_38-DATA9WL3YBYKQV, DATA9WL3YBYKQV_39-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_3A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_3B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_3C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_3D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_3E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_3F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_40-DATA9WL3YBYKQV, DATA9WL3YBYKQV_41-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_42-DATA9WL3YBYKQV, DATA9WL3YBYKQV_43-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_44-DATA9WL3YBYKQV, DATA9WL3YBYKQV_45-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_46-DATA9WL3YBYKQV, DATA9WL3YBYKQV_47-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_48-DATA9WL3YBYKQV, DATA9WL3YBYKQV_49-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_4A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_4B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_4C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_4D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_4E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_4F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_50-DATA9WL3YBYKQV, DATA9WL3YBYKQV_51-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_52-DATA9WL3YBYKQV, DATA9WL3YBYKQV_53-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_54-DATA9WL3YBYKQV, DATA9WL3YBYKQV_55-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_56-DATA9WL3YBYKQV, DATA9WL3YBYKQV_57-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_58-DATA9WL3YBYKQV, DATA9WL3YBYKQV_59-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_5A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_5B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_5C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_5D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_5E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_5F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_60-DATA9WL3YBYKQV, DATA9WL3YBYKQV_61-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_62-DATA9WL3YBYKQV, DATA9WL3YBYKQV_63-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_64-DATA9WL3YBYKQV, DATA9WL3YBYKQV_65-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_66-DATA9WL3YBYKQV, DATA9WL3YBYKQV_67-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_68-DATA9WL3YBYKQV, DATA9WL3YBYKQV_69-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_6A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_6B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_6C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_6D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_6E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_6F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_70-DATA9WL3YBYKQV, DATA9WL3YBYKQV_71-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_72-DATA9WL3YBYKQV, DATA9WL3YBYKQV_73-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_74-DATA9WL3YBYKQV, DATA9WL3YBYKQV_75-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_76-DATA9WL3YBYKQV, DATA9WL3YBYKQV_77-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_78-DATA9WL3YBYKQV, DATA9WL3YBYKQV_79-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_7A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_7B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_7C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_7D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_7E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_7F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_80-DATA9WL3YBYKQV, DATA9WL3YBYKQV_81-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_82-DATA9WL3YBYKQV, DATA9WL3YBYKQV_83-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_84-DATA9WL3YBYKQV, DATA9WL3YBYKQV_85-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_86-DATA9WL3YBYKQV, DATA9WL3YBYKQV_87-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_88-DATA9WL3YBYKQV, DATA9WL3YBYKQV_89-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_8A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_8B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_8C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_8D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_8E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_8F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_90-DATA9WL3YBYKQV, DATA9WL3YBYKQV_91-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_92-DATA9WL3YBYKQV, DATA9WL3YBYKQV_93-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_94-DATA9WL3YBYKQV, DATA9WL3YBYKQV_95-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_96-DATA9WL3YBYKQV, DATA9WL3YBYKQV_97-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_98-DATA9WL3YBYKQV, DATA9WL3YBYKQV_99-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_9A-DATA9WL3YBYKQV, DATA9WL3YBYKQV_9B-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_9C-DATA9WL3YBYKQV, DATA9WL3YBYKQV_9D-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_9E-DATA9WL3YBYKQV, DATA9WL3YBYKQV_9F-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_A0-DATA9WL3YBYKQV, DATA9WL3YBYKQV_A1-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_A2-DATA9WL3YBYKQV, DATA9WL3YBYKQV_A3-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_A4-DATA9WL3YBYKQV, DATA9WL3YBYKQV_A5-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_A6-DATA9WL3YBYKQV, DATA9WL3YBYKQV_A7-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_A8-DATA9WL3YBYKQV, DATA9WL3YBYKQV_A9-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_AA-DATA9WL3YBYKQV, DATA9WL3YBYKQV_AB-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_AC-DATA9WL3YBYKQV, DATA9WL3YBYKQV_AD-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_AE-DATA9WL3YBYKQV, DATA9WL3YBYKQV_AF-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_B0-DATA9WL3YBYKQV, DATA9WL3YBYKQV_B1-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_B2-DATA9WL3YBYKQV, DATA9WL3YBYKQV_B3-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_B4-DATA9WL3YBYKQV, DATA9WL3YBYKQV_B5-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_B6-DATA9WL3YBYKQV, DATA9WL3YBYKQV_B7-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_B8-DATA9WL3YBYKQV, DATA9WL3YBYKQV_B9-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_BA-DATA9WL3YBYKQV, DATA9WL3YBYKQV_BB-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_BC-DATA9WL3YBYKQV, DATA9WL3YBYKQV_BD-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_BE-DATA9WL3YBYKQV, DATA9WL3YBYKQV_BF-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_C0-DATA9WL3YBYKQV, DATA9WL3YBYKQV_C1-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_C2-DATA9WL3YBYKQV, DATA9WL3YBYKQV_C3-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_C4-DATA9WL3YBYKQV, DATA9WL3YBYKQV_C5-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_C6-DATA9WL3YBYKQV, DATA9WL3YBYKQV_C7-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_C8-DATA9WL3YBYKQV, DATA9WL3YBYKQV_C9-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_CA-DATA9WL3YBYKQV, DATA9WL3YBYKQV_CB-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_CC-DATA9WL3YBYKQV, DATA9WL3YBYKQV_CD-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_CE-DATA9WL3YBYKQV, DATA9WL3YBYKQV_CF-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_D0-DATA9WL3YBYKQV, DATA9WL3YBYKQV_D1-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_D2-DATA9WL3YBYKQV, DATA9WL3YBYKQV_D3-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_D4-DATA9WL3YBYKQV, DATA9WL3YBYKQV_D5-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_D6-DATA9WL3YBYKQV, DATA9WL3YBYKQV_D7-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_D8-DATA9WL3YBYKQV, DATA9WL3YBYKQV_D9-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_DA-DATA9WL3YBYKQV, DATA9WL3YBYKQV_DB-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_DC-DATA9WL3YBYKQV, DATA9WL3YBYKQV_DD-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_DE-DATA9WL3YBYKQV, DATA9WL3YBYKQV_DF-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_E0-DATA9WL3YBYKQV, DATA9WL3YBYKQV_E1-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_E2-DATA9WL3YBYKQV, DATA9WL3YBYKQV_E3-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_E4-DATA9WL3YBYKQV, DATA9WL3YBYKQV_E5-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_E6-DATA9WL3YBYKQV, DATA9WL3YBYKQV_E7-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_E8-DATA9WL3YBYKQV, DATA9WL3YBYKQV_E9-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_EA-DATA9WL3YBYKQV, DATA9WL3YBYKQV_EB-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_EC-DATA9WL3YBYKQV, DATA9WL3YBYKQV_ED-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_EE-DATA9WL3YBYKQV, DATA9WL3YBYKQV_EF-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_F0-DATA9WL3YBYKQV, DATA9WL3YBYKQV_F1-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_F2-DATA9WL3YBYKQV, DATA9WL3YBYKQV_F3-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_F4-DATA9WL3YBYKQV, DATA9WL3YBYKQV_F5-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_F6-DATA9WL3YBYKQV, DATA9WL3YBYKQV_F7-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_F8-DATA9WL3YBYKQV, DATA9WL3YBYKQV_F9-DATA9WL3YBYKQV
	dc.w DATA9WL3YBYKQV_FA-DATA9WL3YBYKQV
DATA9WL3YBYKQV_1: dc.b $0, $3
	dc.b $EC, $4, $0, $0, $FF, $F9
	dc.b $F4, $9, $0, $2, $FF, $F1
	dc.b $4, $D, $0, $8, $FF, $F1
DATA9WL3YBYKQV_2: dc.b $0, $3
	dc.b $F0, $D, $0, $0, $FF, $ED
	dc.b $0, $8, $0, $8, $FF, $ED
	dc.b $8, $C, $0, $B, $FF, $ED
DATA9WL3YBYKQV_3: dc.b $0, $2
	dc.b $F0, $A, $0, $0, $FF, $FB
	dc.b $8, $8, $0, $9, $FF, $F3
DATA9WL3YBYKQV_4: dc.b $0, $3
	dc.b $F0, $D, $0, $0, $FF, $F0
	dc.b $0, $8, $0, $8, $FF, $F0
	dc.b $8, $C, $0, $B, $FF, $F0
DATA9WL3YBYKQV_5: dc.b $0, $3
	dc.b $EC, $4, $0, $0, $FF, $F8
	dc.b $F4, $9, $0, $2, $FF, $F0
	dc.b $4, $D, $0, $8, $FF, $F0
DATA9WL3YBYKQV_6: dc.b $0, $3
	dc.b $F0, $D, $0, $0, $FF, $F0
	dc.b $0, $8, $0, $8, $FF, $F0
	dc.b $8, $C, $0, $B, $FF, $F0
DATA9WL3YBYKQV_7: dc.b $0, $2
	dc.b $F0, $A, $0, $0, $FF, $F8
	dc.b $8, $8, $0, $9, $FF, $F0
DATA9WL3YBYKQV_8: dc.b $0, $3
	dc.b $F0, $D, $0, $0, $FF, $F0
	dc.b $0, $8, $0, $8, $FF, $F0
	dc.b $8, $C, $0, $B, $FF, $F0
DATA9WL3YBYKQV_9: dc.b $0, $4
	dc.b $EE, $4, $0, $0, $FF, $F2
	dc.b $F6, $D, $0, $2, $FF, $F2
	dc.b $6, $8, $0, $A, $FF, $FA
	dc.b $E, $8, $0, $D, $FF, $F2
DATA9WL3YBYKQV_A: dc.b $0, $3
	dc.b $F0, $B, $0, $0, $FF, $F1
	dc.b $F8, $6, $0, $C, $0, $9
	dc.b $10, $8, $0, $12, $FF, $F1
DATA9WL3YBYKQV_B: dc.b $0, $4
	dc.b $EA, $4, $0, $0, $FF, $F8
	dc.b $F2, $D, $0, $2, $FF, $F0
	dc.b $2, $8, $0, $A, $FF, $F8
	dc.b $A, $D, $0, $D, $FF, $F0
DATA9WL3YBYKQV_C: dc.b $0, $3
	dc.b $EF, $4, $0, $0, $FF, $F6
	dc.b $F7, $F, $0, $2, $FF, $EE
	dc.b $FF, $0, $0, $12, $0, $E
DATA9WL3YBYKQV_D: dc.b $0, $3
	dc.b $ED, $8, $0, $0, $FF, $F2
	dc.b $F5, $D, $0, $3, $FF, $F2
	dc.b $5, $9, $0, $B, $FF, $F2
DATA9WL3YBYKQV_E: dc.b $0, $3
	dc.b $F2, $4, $0, $0, $FF, $F7
	dc.b $FA, $B, $0, $2, $FF, $EF
	dc.b $2, $5, $0, $E, $0, $7
DATA9WL3YBYKQV_F: dc.b $0, $3
	dc.b $F0, $4, $0, $0, $FF, $F7
	dc.b $F8, $8, $0, $2, $FF, $EF
	dc.b $0, $E, $0, $5, $FF, $EF
DATA9WL3YBYKQV_10: dc.b $0, $4
	dc.b $EC, $0, $0, $0, $FF, $FC
	dc.b $F4, $9, $0, $1, $FF, $F4
	dc.b $4, $C, $0, $7, $FF, $F4
	dc.b $C, $C, $0, $B, $FF, $EC
DATA9WL3YBYKQV_11: dc.b $0, $2
	dc.b $EE, $4, $0, $0, $0, $0
	dc.b $F6, $E, $0, $2, $FF, $F0
DATA9WL3YBYKQV_12: dc.b $0, $2
	dc.b $F2, $E, $0, $0, $FF, $F0
	dc.b $A, $0, $0, $C, $0, $8
DATA9WL3YBYKQV_13: dc.b $0, $2
	dc.b $F2, $8, $0, $0, $FF, $F0
	dc.b $FA, $D, $0, $3, $FF, $F0
DATA9WL3YBYKQV_14: dc.b $0, $1
	dc.b $F4, $E, $0, $0, $FF, $F0
DATA9WL3YBYKQV_15: dc.b $0, $2
	dc.b $ED, $4, $0, $0, $0, $0
	dc.b $F5, $E, $0, $2, $FF, $F0
DATA9WL3YBYKQV_16: dc.b $0, $1
	dc.b $F4, $E, $0, $0, $FF, $F0
DATA9WL3YBYKQV_17: dc.b $0, $2
	dc.b $F1, $8, $0, $0, $FF, $F0
	dc.b $F9, $D, $0, $3, $FF, $F0
DATA9WL3YBYKQV_18: dc.b $0, $1
	dc.b $F4, $E, $0, $0, $FF, $F0
DATA9WL3YBYKQV_19: dc.b $0, $3
	dc.b $EF, $8, $0, $0, $FF, $F5
	dc.b $F7, $E, $0, $3, $FF, $F5
	dc.b $FF, $1, $0, $F, $FF, $ED
DATA9WL3YBYKQV_1A: dc.b $0, $4
	dc.b $E8, $4, $0, $0, $FF, $F8
	dc.b $F0, $8, $0, $2, $FF, $F8
	dc.b $F8, $E, $0, $5, $FF, $F0
	dc.b $F8, $2, $0, $11, $0, $10
DATA9WL3YBYKQV_1B: dc.b $0, $4
	dc.b $F0, $C, $0, $0, $FF, $F1
	dc.b $F8, $C, $0, $4, $FF, $E9
	dc.b $0, $9, $0, $8, $FF, $F1
	dc.b $F8, $6, $0, $E, $0, $9
DATA9WL3YBYKQV_1C: dc.b $0, $3
	dc.b $EA, $0, $0, $0, $FF, $FE
	dc.b $F2, $F, $0, $1, $FF, $F6
	dc.b $FA, $1, $0, $11, $FF, $EE
DATA9WL3YBYKQV_1D: dc.b $0, $3
	dc.b $EF, $4, $0, $0, $FF, $F7
	dc.b $F7, $E, $0, $2, $FF, $EF
	dc.b $F7, $2, $0, $E, $0, $F
DATA9WL3YBYKQV_1E: dc.b $0, $4
	dc.b $E9, $0, $0, $0, $0, $0
	dc.b $F1, $4, $0, $1, $0, $0
	dc.b $F9, $E, $0, $3, $FF, $F8
	dc.b $F9, $1, $0, $F, $FF, $F0
DATA9WL3YBYKQV_1F: dc.b $0, $3
	dc.b $F1, $8, $0, $0, $0, $0
	dc.b $F9, $E, $0, $3, $FF, $F8
	dc.b $F9, $1, $0, $F, $FF, $F0
DATA9WL3YBYKQV_20: dc.b $0, $4
	dc.b $EC, $0, $0, $0, $0, $4
	dc.b $F4, $E, $0, $1, $FF, $F4
	dc.b $FC, $0, $0, $D, $FF, $EC
	dc.b $C, $0, $0, $E, $0, $C
DATA9WL3YBYKQV_21: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F8
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $FF, $F0
DATA9WL3YBYKQV_22: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F8
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $FF, $F0
DATA9WL3YBYKQV_23: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F8
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $FF, $F0
DATA9WL3YBYKQV_24: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F8
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $FF, $F0
DATA9WL3YBYKQV_25: dc.b $0, $3
	dc.b $EC, $4, $0, $0, $FF, $F8
	dc.b $F4, $9, $0, $2, $FF, $F0
	dc.b $4, $5, $0, $8, $FF, $F8
DATA9WL3YBYKQV_26: dc.b $0, $3
	dc.b $ED, $4, $0, $0, $FF, $F8
	dc.b $F5, $9, $0, $2, $FF, $F0
	dc.b $5, $5, $0, $8, $FF, $F8
DATA9WL3YBYKQV_27: dc.b $0, $3
	dc.b $EC, $4, $0, $0, $FF, $F8
	dc.b $F4, $9, $0, $2, $FF, $F0
	dc.b $4, $5, $0, $8, $FF, $F8
DATA9WL3YBYKQV_28: dc.b $0, $3
	dc.b $ED, $4, $0, $0, $FF, $F8
	dc.b $F5, $9, $0, $2, $FF, $F0
	dc.b $5, $5, $0, $8, $FF, $F8
DATA9WL3YBYKQV_29: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F0
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $0, $0
DATA9WL3YBYKQV_2A: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F0
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $0, $0
DATA9WL3YBYKQV_2B: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F0
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $0, $0
DATA9WL3YBYKQV_2C: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F0
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $0, $0
DATA9WL3YBYKQV_2D: dc.b $0, $3
	dc.b $F8, $D, $0, $0, $FF, $EC
	dc.b $F8, $1, $0, $8, $0, $C
	dc.b $8, $4, $0, $A, $FF, $F4
DATA9WL3YBYKQV_2E: dc.b $0, $3
	dc.b $F8, $D, $0, $0, $FF, $EB
	dc.b $F8, $1, $0, $8, $0, $B
	dc.b $8, $4, $0, $A, $FF, $F3
DATA9WL3YBYKQV_2F: dc.b $0, $3
	dc.b $F8, $D, $0, $0, $FF, $EC
	dc.b $F8, $1, $0, $8, $0, $C
	dc.b $8, $4, $0, $A, $FF, $F4
DATA9WL3YBYKQV_30: dc.b $0, $3
	dc.b $F8, $D, $0, $0, $FF, $EB
	dc.b $F8, $1, $0, $8, $0, $B
	dc.b $8, $4, $0, $A, $FF, $F3
DATA9WL3YBYKQV_31: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F1
DATA9WL3YBYKQV_32: dc.b $0, $2
	dc.b $EC, $B, $0, $0, $FF, $F1
	dc.b $C, $4, $0, $C, $FF, $F1
DATA9WL3YBYKQV_33: dc.b $0, $1
	dc.b $ED, $B, $0, $0, $FF, $F3
DATA9WL3YBYKQV_34: dc.b $0, $1
	dc.b $F8, $A, $0, $0, $FF, $F3
DATA9WL3YBYKQV_35: dc.b $0, $2
	dc.b $F3, $A, $0, $0, $FF, $F3
	dc.b $B, $0, $0, $9, $0, $3
DATA9WL3YBYKQV_36: dc.b $0, $2
	dc.b $EF, $4, $0, $0, $FF, $F2
	dc.b $F7, $A, $0, $2, $FF, $F2
DATA9WL3YBYKQV_37: dc.b $0, $2
	dc.b $F2, $4, $0, $0, $FF, $F2
	dc.b $FA, $A, $0, $2, $FF, $F2
DATA9WL3YBYKQV_38: dc.b $0, $2
	dc.b $F0, $4, $0, $0, $FF, $F4
	dc.b $F8, $A, $0, $2, $FF, $F4
DATA9WL3YBYKQV_39: dc.b $0, $2
	dc.b $EE, $4, $0, $0, $FF, $F4
	dc.b $F6, $A, $0, $2, $FF, $F4
DATA9WL3YBYKQV_3A: dc.b $0, $2
	dc.b $F4, $9, $0, $0, $FF, $F1
	dc.b $4, $4, $0, $6, $FF, $F9
DATA9WL3YBYKQV_3B: dc.b $0, $2
	dc.b $F4, $A, $0, $0, $FF, $F1
	dc.b $C, $0, $0, $9, $FF, $F1
DATA9WL3YBYKQV_3C: dc.b $0, $2
	dc.b $F1, $9, $0, $0, $FF, $F4
	dc.b $1, $5, $0, $6, $FF, $F4
DATA9WL3YBYKQV_3D: dc.b $0, $2
	dc.b $F1, $A, $0, $0, $FF, $F2
	dc.b $9, $4, $0, $9, $FF, $FA
DATA9WL3YBYKQV_3E: dc.b $0, $2
	dc.b $ED, $0, $0, $0, $0, $1
	dc.b $F5, $A, $0, $1, $FF, $F1
DATA9WL3YBYKQV_3F: dc.b $0, $1
	dc.b $F3, $A, $0, $0, $FF, $F3
DATA9WL3YBYKQV_40: dc.b $0, $3
	dc.b $EE, $4, $0, $0, $FF, $F2
	dc.b $F6, $9, $0, $2, $FF, $F2
	dc.b $6, $4, $0, $8, $FF, $FA
DATA9WL3YBYKQV_41: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F1
DATA9WL3YBYKQV_42: dc.b $0, $1
	dc.b $F1, $B, $0, $0, $FF, $F0
DATA9WL3YBYKQV_43: dc.b $0, $3
	dc.b $F0, $8, $0, $0, $FF, $F4
	dc.b $F8, $4, $0, $3, $FF, $F4
	dc.b $0, $9, $0, $5, $FF, $F4
DATA9WL3YBYKQV_44: dc.b $0, $2
	dc.b $EC, $0, $0, $0, $FF, $F9
	dc.b $F4, $A, $0, $1, $FF, $F1
DATA9WL3YBYKQV_45: dc.b $0, $2
	dc.b $F4, $9, $0, $0, $FF, $F1
	dc.b $4, $0, $0, $6, $FF, $F1
DATA9WL3YBYKQV_46: dc.b $0, $2
	dc.b $F2, $4, $0, $0, $FF, $F7
	dc.b $FA, $9, $0, $2, $FF, $EF
DATA9WL3YBYKQV_47: dc.b $0, $3
	dc.b $ED, $4, $0, $0, $FF, $F5
	dc.b $F5, $9, $0, $2, $FF, $F5
	dc.b $5, $4, $0, $8, $FF, $F5
DATA9WL3YBYKQV_48: dc.b $0, $2
	dc.b $EF, $A, $0, $0, $FF, $F1
	dc.b $7, $4, $0, $9, $FF, $F9
DATA9WL3YBYKQV_49: dc.b $0, $3
	dc.b $F2, $8, $0, $0, $FF, $F5
	dc.b $FA, $D, $0, $3, $FF, $ED
	dc.b $FA, $0, $0, $B, $0, $D
DATA9WL3YBYKQV_4A: dc.b $0, $2
	dc.b $F2, $8, $0, $0, $FF, $F8
	dc.b $FA, $D, $0, $3, $FF, $F0
DATA9WL3YBYKQV_4B: dc.b $0, $3
	dc.b $F2, $4, $0, $0, $FF, $F7
	dc.b $FA, $8, $0, $2, $FF, $F7
	dc.b $2, $C, $0, $5, $FF, $EF
DATA9WL3YBYKQV_4C: dc.b $0, $2
	dc.b $F0, $4, $0, $0, $FF, $FC
	dc.b $F8, $A, $0, $2, $FF, $F4
DATA9WL3YBYKQV_4D: dc.b $0, $3
	dc.b $F0, $4, $0, $0, $FF, $FC
	dc.b $F8, $9, $0, $2, $FF, $F4
	dc.b $8, $4, $0, $8, $FF, $F4
DATA9WL3YBYKQV_4E: dc.b $0, $4
	dc.b $EA, $0, $0, $0, $0, $0
	dc.b $F2, $4, $0, $1, $0, $0
	dc.b $FA, $C, $0, $3, $FF, $F0
	dc.b $2, $9, $0, $7, $FF, $F0
DATA9WL3YBYKQV_4F: dc.b $0, $4
	dc.b $ED, $4, $0, $0, $0, $0
	dc.b $F5, $C, $0, $2, $FF, $F0
	dc.b $FD, $9, $0, $6, $FF, $F0
	dc.b $D, $4, $0, $C, $FF, $F8
DATA9WL3YBYKQV_50: dc.b $0, $4
	dc.b $EB, $4, $0, $0, $FF, $F9
	dc.b $F3, $C, $0, $2, $FF, $F1
	dc.b $FB, $9, $0, $6, $FF, $F1
	dc.b $B, $0, $0, $C, $FF, $F9
DATA9WL3YBYKQV_51: dc.b $0, $3
	dc.b $EF, $4, $0, $0, $FF, $FA
	dc.b $F7, $9, $0, $2, $FF, $F2
	dc.b $7, $4, $0, $8, $FF, $FA
DATA9WL3YBYKQV_52: dc.b $0, $3
	dc.b $F4, $4, $0, $0, $FF, $F8
	dc.b $FC, $C, $0, $2, $FF, $F0
	dc.b $4, $4, $0, $6, $FF, $F8
DATA9WL3YBYKQV_53: dc.b $0, $2
	dc.b $F4, $D, $0, $0, $FF, $F0
	dc.b $4, $8, $0, $8, $FF, $F0
DATA9WL3YBYKQV_54: dc.b $0, $2
	dc.b $F3, $8, $0, $0, $FF, $F6
	dc.b $FB, $D, $0, $3, $FF, $EE
DATA9WL3YBYKQV_55: dc.b $0, $3
	dc.b $F0, $8, $0, $0, $FF, $F8
	dc.b $F8, $C, $0, $3, $FF, $F0
	dc.b $0, $9, $0, $7, $FF, $F0
DATA9WL3YBYKQV_56: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F3
DATA9WL3YBYKQV_57: dc.b $0, $3
	dc.b $F0, $8, $0, $0, $FF, $F7
	dc.b $F8, $5, $0, $3, $FF, $F7
	dc.b $8, $8, $0, $7, $FF, $F7
DATA9WL3YBYKQV_58: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F3
DATA9WL3YBYKQV_59: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F3
DATA9WL3YBYKQV_5A: dc.b $0, $3
	dc.b $F0, $4, $0, $0, $FF, $F7
	dc.b $F8, $9, $0, $2, $FF, $F7
	dc.b $8, $4, $0, $8, $FF, $F7
DATA9WL3YBYKQV_5B: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_5C: dc.b $0, $4
	dc.b $F4, $8, $0, $0, $FF, $F0
	dc.b $F4, $4, $0, $3, $0, $10
	dc.b $FC, $D, $0, $5, $FF, $F0
	dc.b $FC, $5, $0, $D, $0, $10
DATA9WL3YBYKQV_5D: dc.b $0, $1
	dc.b $F4, $E, $0, $0, $FF, $FD
DATA9WL3YBYKQV_5E: dc.b $0, $3
	dc.b $F4, $E, $0, $0, $FF, $F1
	dc.b $F4, $0, $0, $C, $FF, $E9
	dc.b $4, $0, $0, $D, $FF, $E9
DATA9WL3YBYKQV_5F: dc.b $0, $2
	dc.b $F4, $E, $0, $0, $FF, $F1
	dc.b $F4, $6, $0, $C, $FF, $E1
DATA9WL3YBYKQV_60: dc.b $0, $1
	dc.b $F4, $E, $0, $0, $FF, $F4
DATA9WL3YBYKQV_61: dc.b $0, $1
	dc.b $F4, $E, $0, $0, $FF, $E6
DATA9WL3YBYKQV_62: dc.b $0, $3
	dc.b $F4, $8, $0, $0, $FF, $F4
	dc.b $FC, $D, $0, $3, $FF, $EC
	dc.b $FC, $1, $0, $B, $0, $C
DATA9WL3YBYKQV_63: dc.b $0, $4
	dc.b $E8, $A, $0, $0, $FF, $F5
	dc.b $0, $4, $0, $9, $FF, $F5
	dc.b $8, $8, $0, $B, $FF, $F5
	dc.b $10, $8, $0, $E, $FF, $F5
DATA9WL3YBYKQV_64: dc.b $0, $1
	dc.b $F1, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_65: dc.b $0, $2
	dc.b $E9, $B, $0, $0, $FF, $F4
	dc.b $9, $8, $0, $C, $FF, $F4
DATA9WL3YBYKQV_66: dc.b $0, $2
	dc.b $E7, $B, $0, $0, $FF, $F4
	dc.b $7, $9, $0, $C, $FF, $F4
DATA9WL3YBYKQV_67: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_68: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_69: dc.b $0, $3
	dc.b $EF, $8, $0, $0, $FF, $F7
	dc.b $F7, $E, $0, $3, $FF, $EF
	dc.b $7, $0, $0, $F, $0, $F
DATA9WL3YBYKQV_6A: dc.b $0, $3
	dc.b $EE, $4, $0, $0, $FF, $F7
	dc.b $F6, $D, $0, $2, $FF, $EF
	dc.b $6, $8, $0, $A, $FF, $F7
DATA9WL3YBYKQV_6B: dc.b $0, $2
	dc.b $EE, $4, $0, $0, $FF, $F3
	dc.b $F6, $A, $0, $2, $FF, $F3
DATA9WL3YBYKQV_6C: dc.b $0, $2
	dc.b $F1, $8, $0, $0, $FF, $EE
	dc.b $F9, $D, $0, $3, $FF, $EE
DATA9WL3YBYKQV_6D: dc.b $0, $2
	dc.b $F3, $8, $0, $0, $FF, $EF
	dc.b $FB, $D, $0, $3, $FF, $EF
DATA9WL3YBYKQV_6E: dc.b $0, $2
	dc.b $F8, $D, $0, $0, $FF, $F1
	dc.b $8, $8, $0, $8, $FF, $F9
DATA9WL3YBYKQV_6F: dc.b $0, $2
	dc.b $F6, $9, $0, $0, $FF, $F4
	dc.b $6, $4, $0, $6, $FF, $FC
DATA9WL3YBYKQV_70: dc.b $0, $2
	dc.b $F6, $9, $0, $0, $FF, $F4
	dc.b $6, $C, $0, $6, $FF, $EC
DATA9WL3YBYKQV_71: dc.b $0, $2
	dc.b $F7, $D, $0, $0, $FF, $EF
	dc.b $7, $8, $0, $8, $FF, $EF
DATA9WL3YBYKQV_72: dc.b $0, $1
	dc.b $F6, $E, $0, $0, $FF, $EF
DATA9WL3YBYKQV_73: dc.b $0, $2
	dc.b $F6, $E, $0, $0, $FF, $F7
	dc.b $FE, $1, $0, $C, $FF, $EF
DATA9WL3YBYKQV_74: dc.b $0, $1
	dc.b $F5, $E, $0, $0, $FF, $F2
DATA9WL3YBYKQV_75: dc.b $0, $1
	dc.b $F7, $A, $0, $0, $FF, $F2
DATA9WL3YBYKQV_76: dc.b $0, $2
	dc.b $F4, $8, $0, $0, $FF, $F2
	dc.b $FC, $D, $0, $3, $FF, $F2
DATA9WL3YBYKQV_77: dc.b $0, $2
	dc.b $F3, $8, $0, $0, $FF, $F0
	dc.b $FB, $D, $0, $3, $FF, $F0
DATA9WL3YBYKQV_78: dc.b $0, $4
	dc.b $E6, $C, $0, $0, $FF, $F2
	dc.b $EE, $9, $0, $4, $FF, $F2
	dc.b $FE, $C, $0, $A, $FF, $F2
	dc.b $6, $8, $0, $E, $FF, $FA
DATA9WL3YBYKQV_79: dc.b $0, $4
	dc.b $E2, $4, $0, $0, $FF, $EE
	dc.b $EA, $9, $0, $2, $FF, $E6
	dc.b $F2, $1, $0, $8, $0, $6
	dc.b $FA, $9, $0, $A, $FF, $EE
DATA9WL3YBYKQV_7A: dc.b $0, $4
	dc.b $EE, $0, $0, $0, $FF, $E4
	dc.b $EE, $6, $0, $1, $FF, $FC
	dc.b $F6, $9, $0, $7, $FF, $E4
	dc.b $6, $C, $0, $D, $FF, $E4
DATA9WL3YBYKQV_7B: dc.b $0, $4
	dc.b $F4, $4, $0, $0, $FF, $F1
	dc.b $FC, $6, $0, $2, $FF, $F9
	dc.b $4, $9, $0, $8, $FF, $E1
	dc.b $14, $4, $0, $E, $FF, $E9
DATA9WL3YBYKQV_7C: dc.b $0, $4
	dc.b $14, $C, $18, $0, $FF, $EE
	dc.b $4, $9, $18, $4, $FF, $F6
	dc.b $FC, $C, $18, $A, $FF, $EE
	dc.b $F4, $8, $18, $E, $FF, $EE
DATA9WL3YBYKQV_7D: dc.b $0, $4
	dc.b $16, $4, $18, $0, $0, $3
	dc.b $6, $9, $18, $2, $0, $3
	dc.b $FE, $1, $18, $8, $FF, $F3
	dc.b $F6, $9, $18, $A, $FF, $FB
DATA9WL3YBYKQV_7E: dc.b $0, $4
	dc.b $A, $0, $18, $0, $0, $15
	dc.b $FA, $6, $18, $1, $FF, $F5
	dc.b $FA, $9, $0, $7, $0, $5
	dc.b $F2, $C, $18, $D, $FF, $FD
DATA9WL3YBYKQV_7F: dc.b $0, $4
	dc.b $5, $4, $18, $0, $0, $1
	dc.b $ED, $6, $18, $2, $FF, $F9
	dc.b $ED, $9, $18, $8, $0, $9
	dc.b $E5, $4, $18, $E, $0, $9
DATA9WL3YBYKQV_80: dc.b $0, $2
	dc.b $E8, $D, $0, $0, $FF, $EF
	dc.b $F8, $A, $0, $8, $FF, $EF
DATA9WL3YBYKQV_81: dc.b $0, $4
	dc.b $E9, $C, $0, $0, $FF, $EE
	dc.b $F1, $8, $0, $4, $FF, $EE
	dc.b $F9, $E, $0, $7, $FF, $E6
	dc.b $11, $4, $0, $13, $FF, $EE
DATA9WL3YBYKQV_82: dc.b $0, $4
	dc.b $E9, $A, $0, $0, $FF, $F6
	dc.b $F9, $4, $0, $9, $FF, $E6
	dc.b $1, $C, $0, $B, $FF, $E6
	dc.b $9, $5, $0, $F, $FF, $F6
DATA9WL3YBYKQV_83: dc.b $0, $3
	dc.b $E8, $F, $0, $0, $FF, $EC
	dc.b $E8, $0, $0, $10, $0, $C
	dc.b $8, $8, $0, $11, $FF, $F4
DATA9WL3YBYKQV_84: dc.b $0, $3
	dc.b $E9, $9, $0, $0, $FF, $F6
	dc.b $F9, $D, $0, $6, $FF, $E6
	dc.b $9, $5, $0, $E, $FF, $F6
DATA9WL3YBYKQV_85: dc.b $0, $4
	dc.b $E9, $9, $0, $0, $FF, $F5
	dc.b $F9, $C, $0, $6, $FF, $ED
	dc.b $1, $8, $0, $A, $FF, $ED
	dc.b $9, $5, $0, $D, $FF, $F5
DATA9WL3YBYKQV_86: dc.b $0, $2
	dc.b $F8, $C, $0, $0, $FF, $F8
	dc.b $0, $9, $0, $4, $FF, $F8
DATA9WL3YBYKQV_87: dc.b $0, $2
	dc.b $F8, $D, $0, $0, $FF, $F8
	dc.b $8, $8, $0, $8, $FF, $F8
DATA9WL3YBYKQV_88: dc.b $0, $2
	dc.b $F8, $C, $0, $0, $FF, $F8
	dc.b $0, $9, $0, $4, $FF, $F8
DATA9WL3YBYKQV_89: dc.b $0, $1
	dc.b $F0, $F, $0, $0, $FF, $F0
DATA9WL3YBYKQV_8A: dc.b $0, $1
	dc.b $F0, $F, $0, $0, $FF, $F0
DATA9WL3YBYKQV_8B: dc.b $0, $2
	dc.b $E9, $5, $0, $0, $FF, $F9
	dc.b $F9, $B, $0, $4, $FF, $F1
DATA9WL3YBYKQV_8C: dc.b $0, $2
	dc.b $E9, $5, $0, $0, $FF, $F9
	dc.b $F9, $B, $0, $4, $FF, $F1
DATA9WL3YBYKQV_8D: dc.b $0, $2
	dc.b $EE, $4, $0, $0, $FF, $F6
	dc.b $F6, $E, $0, $2, $FF, $EE
DATA9WL3YBYKQV_8E: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F0
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $8, $0, $A, $FF, $F8
DATA9WL3YBYKQV_8F: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F0
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $8, $0, $A, $FF, $F8
DATA9WL3YBYKQV_90: dc.b $0, $2
	dc.b $E9, $B, $0, $0, $FF, $F5
	dc.b $7, $4, $0, $C, $FF, $FD
DATA9WL3YBYKQV_91: dc.b $0, $2
	dc.b $E9, $9, $0, $0, $FF, $F5
	dc.b $F9, $D, $0, $6, $FF, $F5
DATA9WL3YBYKQV_92: dc.b $0, $2
	dc.b $E9, $9, $0, $0, $FF, $F5
	dc.b $F9, $D, $0, $6, $FF, $F5
DATA9WL3YBYKQV_93: dc.b $0, $1
	dc.b $E9, $A, $0, $0, $FF, $F5
DATA9WL3YBYKQV_94: dc.b $0, $3
	dc.b $E9, $D, $0, $0, $FF, $F1
	dc.b $EC, $B, $0, $8, $FF, $F4
	dc.b $C, $8, $0, $14, $FF, $F4
DATA9WL3YBYKQV_95: dc.b $0, $3
	dc.b $E8, $9, $0, $0, $FF, $F5
	dc.b $EC, $B, $0, $6, $FF, $F4
	dc.b $C, $8, $0, $12, $FF, $F4
DATA9WL3YBYKQV_96: dc.b $0, $1
	dc.b $F0, $F, $0, $0, $FF, $F0
DATA9WL3YBYKQV_97: dc.b $0, $1
	dc.b $F0, $F, $0, $0, $FF, $F0
DATA9WL3YBYKQV_98: dc.b $0, $1
	dc.b $F0, $F, $0, $0, $FF, $F0
DATA9WL3YBYKQV_99: dc.b $0, $1
	dc.b $F8, $A, $0, $0, $FF, $FA
DATA9WL3YBYKQV_9A: dc.b $0, $3
	dc.b $F0, $8, $0, $0, $FF, $F2
	dc.b $F8, $D, $0, $3, $FF, $EA
	dc.b $8, $4, $0, $B, $FF, $F2
DATA9WL3YBYKQV_9B: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F1
	dc.b $0, $C, $0, $6, $FF, $E9
	dc.b $8, $8, $0, $A, $FF, $E9
DATA9WL3YBYKQV_9C: dc.b $0, $1
	dc.b $F0, $F, $0, $0, $FF, $F1
DATA9WL3YBYKQV_9D: dc.b $0, $2
	dc.b $EE, $7, $0, $0, $FF, $E6
	dc.b $F6, $A, $0, $8, $FF, $F6
DATA9WL3YBYKQV_9E: dc.b $0, $3
	dc.b $EE, $4, $0, $0, $FF, $EE
	dc.b $F6, $E, $0, $2, $FF, $E6
	dc.b $F6, $2, $0, $E, $0, $6
DATA9WL3YBYKQV_9F: dc.b $0, $3
	dc.b $F1, $8, $0, $0, $FF, $F6
	dc.b $F9, $D, $0, $3, $FF, $EE
	dc.b $9, $8, $0, $B, $FF, $EE
DATA9WL3YBYKQV_A0: dc.b $0, $2
	dc.b $ED, $8, $0, $0, $FF, $F3
	dc.b $F5, $E, $0, $3, $FF, $EB
DATA9WL3YBYKQV_A1: dc.b $0, $2
	dc.b $ED, $8, $0, $0, $FF, $F3
	dc.b $F5, $E, $0, $3, $FF, $EB
DATA9WL3YBYKQV_A2: dc.b $0, $2
	dc.b $ED, $8, $0, $0, $FF, $F3
	dc.b $F5, $E, $0, $3, $FF, $EB
DATA9WL3YBYKQV_A3: dc.b $0, $2
	dc.b $ED, $8, $0, $0, $FF, $F3
	dc.b $F5, $E, $0, $3, $FF, $EB
DATA9WL3YBYKQV_A4: dc.b $0, $2
	dc.b $ED, $8, $0, $0, $FF, $F3
	dc.b $F5, $E, $0, $3, $FF, $EB
DATA9WL3YBYKQV_A5: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_A6: dc.b $0, $4
	dc.b $E8, $0, $0, $0, $FF, $FE
	dc.b $F0, $D, $0, $1, $FF, $EE
	dc.b $0, $D, $0, $9, $FF, $E6
	dc.b $8, $0, $0, $11, $0, $6
DATA9WL3YBYKQV_A7: dc.b $0, $2
	dc.b $ED, $D, $0, $0, $FF, $F2
	dc.b $FD, $A, $0, $8, $FF, $F2
DATA9WL3YBYKQV_A8: dc.b $0, $3
	dc.b $ED, $8, $0, $0, $FF, $F2
	dc.b $F5, $D, $0, $3, $FF, $F2
	dc.b $5, $9, $0, $B, $FF, $F2
DATA9WL3YBYKQV_A9: dc.b $0, $2
	dc.b $F0, $A, $0, $0, $FF, $F6
	dc.b $8, $C, $0, $9, $FF, $EE
DATA9WL3YBYKQV_AA: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F6
DATA9WL3YBYKQV_AB: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F6
DATA9WL3YBYKQV_AC: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F6
DATA9WL3YBYKQV_AD: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_AE: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_AF: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_B0: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_B1: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_B2: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_B3: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_B4: dc.b $0, $1
	dc.b $F0, $B, $0, $0, $FF, $F4
DATA9WL3YBYKQV_B5: dc.b $0, $3
	dc.b $F0, $0, $0, $0, $0, $0
	dc.b $F8, $D, $0, $1, $FF, $E8
	dc.b $F8, $5, $0, $9, $0, $8
DATA9WL3YBYKQV_B6: dc.b $0, $2
	dc.b $F0, $A, $0, $0, $FF, $FC
	dc.b $F8, $5, $0, $9, $FF, $EC
DATA9WL3YBYKQV_B7: dc.b $0, $1
	dc.b $F0, $E, $0, $0, $FF, $F0
DATA9WL3YBYKQV_B8: dc.b $0, $2
	dc.b $F0, $A, $8, $0, $FF, $EC
	dc.b $F8, $5, $8, $9, $0, $4
DATA9WL3YBYKQV_B9: dc.b $0, $3
	dc.b $F0, $0, $8, $0, $FF, $F8
	dc.b $F8, $D, $8, $1, $FF, $F8
	dc.b $F8, $5, $8, $9, $FF, $E8
DATA9WL3YBYKQV_BA: dc.b $0, $3
	dc.b $F0, $4, $0, $0, $FF, $F4
	dc.b $F8, $D, $0, $2, $FF, $EC
	dc.b $F8, $1, $0, $A, $0, $C
DATA9WL3YBYKQV_BB: dc.b $0, $2
	dc.b $F0, $9, $0, $0, $FF, $F0
	dc.b $0, $C, $0, $6, $FF, $F0
DATA9WL3YBYKQV_BC: dc.b $0, $3
	dc.b $F0, $4, $8, $0, $FF, $FC
	dc.b $F8, $D, $8, $2, $FF, $F4
	dc.b $F8, $1, $8, $A, $FF, $EC
DATA9WL3YBYKQV_BD: dc.b $0, $3
	dc.b $F2, $1, $0, $0, $FF, $EA
	dc.b $F2, $E, $0, $2, $FF, $F2
	dc.b $A, $8, $0, $E, $FF, $F2
DATA9WL3YBYKQV_BE: dc.b $0, $3
	dc.b $F2, $E, $0, $0, $FF, $F4
	dc.b $F2, $1, $0, $C, $FF, $EC
	dc.b $A, $8, $0, $E, $FF, $F4
DATA9WL3YBYKQV_BF: dc.b $0, $2
	dc.b $F2, $F, $0, $0, $FF, $EE
	dc.b $2, $0, $0, $10, $0, $E
DATA9WL3YBYKQV_C0: dc.b $0, $4
	dc.b $F2, $D, $0, $0, $FF, $F2
	dc.b $F2, $0, $0, $8, $FF, $EA
	dc.b $2, $D, $0, $9, $FF, $EA
	dc.b $2, $0, $0, $11, $0, $A
DATA9WL3YBYKQV_C1: dc.b $0, $2
	dc.b $F2, $F, $0, $0, $FF, $ED
	dc.b $F2, $1, $0, $10, $0, $D
DATA9WL3YBYKQV_C2: dc.b $0, $3
	dc.b $F5, $E, $0, $0, $FF, $F3
	dc.b $F5, $2, $0, $C, $FF, $EB
	dc.b $ED, $4, $0, $F, $FF, $EB
DATA9WL3YBYKQV_C3: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F8
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $FF, $F0
DATA9WL3YBYKQV_C4: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F8
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $FF, $F0
DATA9WL3YBYKQV_C5: dc.b $0, $3
	dc.b $EC, $4, $0, $0, $FF, $F8
	dc.b $F4, $9, $0, $2, $FF, $F0
	dc.b $4, $5, $0, $8, $FF, $F8
DATA9WL3YBYKQV_C6: dc.b $0, $3
	dc.b $EC, $4, $0, $0, $FF, $F8
	dc.b $F4, $9, $0, $2, $FF, $F0
	dc.b $4, $5, $0, $8, $FF, $F8
DATA9WL3YBYKQV_C7: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F0
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $0, $0
DATA9WL3YBYKQV_C8: dc.b $0, $3
	dc.b $F0, $9, $0, $0, $FF, $F0
	dc.b $0, $C, $0, $6, $FF, $F0
	dc.b $8, $4, $0, $A, $0, $0
DATA9WL3YBYKQV_C9: dc.b $0, $3
	dc.b $F8, $D, $0, $0, $FF, $EC
	dc.b $F8, $1, $0, $8, $0, $C
	dc.b $8, $4, $0, $A, $FF, $F4
DATA9WL3YBYKQV_CA: dc.b $0, $3
	dc.b $F8, $D, $0, $0, $FF, $EC
	dc.b $F8, $1, $0, $8, $0, $C
	dc.b $8, $4, $0, $A, $FF, $F4
DATA9WL3YBYKQV_CB: dc.b $0, $1
	dc.b $F8, $F, $0, $0, $FF, $F0
DATA9WL3YBYKQV_CC: dc.b $0, $1
	dc.b $F8, $F, $0, $0, $FF, $F0
DATA9WL3YBYKQV_CD: dc.b $0, $3
	dc.b $ED, $4, $0, $0, $FF, $EB
	dc.b $F5, $E, $0, $2, $FF, $F3
	dc.b $5, $0, $0, $E, $FF, $EB
DATA9WL3YBYKQV_CE: dc.b $0, $3
	dc.b $ED, $4, $0, $0, $FF, $F3
	dc.b $F5, $E, $0, $2, $FF, $F3
	dc.b $5, $0, $0, $E, $FF, $EB
DATA9WL3YBYKQV_CF: dc.b $0, $2
	dc.b $E6, $4, $0, $0, $FF, $F4
	dc.b $EE, $B, $0, $2, $FF, $F4
DATA9WL3YBYKQV_D0: dc.b $0, $2
	dc.b $E6, $4, $0, $0, $FF, $F4
	dc.b $EE, $B, $0, $2, $FF, $F4
DATA9WL3YBYKQV_D1: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_D2: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_D3: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_D4: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_D5: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_D6: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_D7: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_D8: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_D9: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_DA: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_DB: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_DC: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_DD: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_DE: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_DF: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F0
	dc.b $FC, $C, $0, $6, $FF, $F0
	dc.b $4, $1, $0, $A, $0, $0
DATA9WL3YBYKQV_E0: dc.b $0, $2
	dc.b $EF, $4, $0, $0, $FF, $F4
	dc.b $F7, $A, $0, $2, $FF, $F4
DATA9WL3YBYKQV_E1: dc.b $0, $3
	dc.b $EC, $4, $0, $0, $FF, $F6
	dc.b $F4, $A, $0, $2, $FF, $F6
	dc.b $C, $4, $0, $B, $FF, $FE
DATA9WL3YBYKQV_E2: dc.b $0, $2
	dc.b $EC, $B, $0, $0, $FF, $F4
	dc.b $C, $0, $0, $C, $FF, $FC
DATA9WL3YBYKQV_E3: dc.b $0, $4
	dc.b $EC, $8, $0, $0, $FF, $F2
	dc.b $F4, $D, $0, $3, $FF, $F2
	dc.b $4, $8, $0, $B, $FF, $FA
	dc.b $C, $0, $0, $E, $FF, $FA
DATA9WL3YBYKQV_E4: dc.b $0, $4
	dc.b $EC, $8, $0, $0, $FF, $F6
	dc.b $F4, $D, $0, $3, $FF, $EE
	dc.b $4, $8, $0, $B, $FF, $F6
	dc.b $C, $4, $0, $E, $FF, $FE
DATA9WL3YBYKQV_E5: dc.b $0, $3
	dc.b $EC, $A, $0, $0, $FF, $F4
	dc.b $4, $C, $0, $9, $FF, $F4
	dc.b $C, $8, $0, $D, $FF, $FC
DATA9WL3YBYKQV_E6: dc.b $0, $2
	dc.b $EC, $A, $0, $0, $FF, $F4
	dc.b $4, $5, $0, $9, $FF, $FC
DATA9WL3YBYKQV_E7: dc.b $0, $3
	dc.b $EC, $A, $0, $0, $FF, $F5
	dc.b $4, $0, $0, $9, $FF, $FD
	dc.b $C, $4, $0, $A, $FF, $FD
DATA9WL3YBYKQV_E8: dc.b $0, $2
	dc.b $EC, $B, $0, $0, $FF, $F4
	dc.b $C, $4, $0, $C, $FF, $F4
DATA9WL3YBYKQV_E9: dc.b $0, $3
	dc.b $EC, $9, $0, $0, $FF, $F2
	dc.b $FC, $5, $0, $6, $FF, $FA
	dc.b $C, $8, $0, $A, $FF, $F2
DATA9WL3YBYKQV_EA: dc.b $0, $3
	dc.b $EC, $A, $0, $0, $FF, $F5
	dc.b $4, $0, $0, $9, $FF, $FD
	dc.b $C, $4, $0, $A, $FF, $FD
DATA9WL3YBYKQV_EB: dc.b $0, $1
	dc.b $F4, $A, $0, $0, $FF, $F4
DATA9WL3YBYKQV_EC: dc.b $0, $3
	dc.b $EC, $8, $0, $0, $FF, $F0
	dc.b $F4, $D, $0, $3, $FF, $F0
	dc.b $4, $9, $0, $B, $FF, $F0
DATA9WL3YBYKQV_ED: dc.b $0, $3
	dc.b $EC, $8, $0, $0, $FF, $F0
	dc.b $F4, $D, $0, $3, $FF, $F0
	dc.b $4, $9, $0, $B, $FF, $F0
DATA9WL3YBYKQV_EE: dc.b $0, $3
	dc.b $EC, $8, $0, $0, $FF, $F0
	dc.b $F4, $D, $0, $3, $FF, $F0
	dc.b $4, $9, $0, $B, $FF, $F0
DATA9WL3YBYKQV_EF: dc.b $0, $2
	dc.b $F0, $E, $0, $0, $FF, $F0
	dc.b $8, $4, $0, $C, $FF, $F0
DATA9WL3YBYKQV_F0: dc.b $0, $2
	dc.b $F0, $E, $0, $0, $FF, $F0
	dc.b $8, $8, $0, $C, $FF, $F0
DATA9WL3YBYKQV_F1: dc.b $0, $2
	dc.b $F0, $E, $0, $0, $FF, $F0
	dc.b $8, $8, $0, $C, $FF, $F0
DATA9WL3YBYKQV_F2: dc.b $0, $1
	dc.b $F0, $F, $0, $0, $FF, $F0
DATA9WL3YBYKQV_F3: dc.b $0, $2
	dc.b $F0, $E, $8, $0, $FF, $F0
	dc.b $8, $8, $8, $C, $FF, $F8
DATA9WL3YBYKQV_F4: dc.b $0, $2
	dc.b $F0, $E, $8, $0, $FF, $F0
	dc.b $8, $8, $8, $C, $FF, $F8
DATA9WL3YBYKQV_F5: dc.b $0, $2
	dc.b $F0, $E, $8, $0, $FF, $F0
	dc.b $8, $4, $8, $C, $0, $0
DATA9WL3YBYKQV_F6: dc.b $0, $2
	dc.b $F0, $E, $0, $0, $FF, $F0
	dc.b $8, $4, $0, $C, $0, $0
DATA9WL3YBYKQV_F7: dc.b $0, $2
	dc.b $F0, $E, $0, $0, $FF, $F0
	dc.b $8, $8, $0, $C, $FF, $F8
DATA9WL3YBYKQV_F8: dc.b $0, $1
	dc.b $F0, $F, $0, $0, $FF, $F0
DATA9WL3YBYKQV_F9: dc.b $0, $2
	dc.b $F0, $E, $8, $0, $FF, $F0
	dc.b $8, $8, $8, $C, $FF, $F0
DATA9WL3YBYKQV_FA: dc.b $0, $2
	dc.b $F0, $E, $8, $0, $FF, $F0
	dc.b $8, $4, $8, $C, $FF, $F0
	even