; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Jan 31 2021 10:49:54 GMT-0600 (Central Standard Time)
; ================================================================================

DATARKIGS4THFV8:
	dc.w $0, DATARKIGS4THFV8_1-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_2-DATARKIGS4THFV8, DATARKIGS4THFV8_3-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_4-DATARKIGS4THFV8, DATARKIGS4THFV8_5-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_6-DATARKIGS4THFV8, DATARKIGS4THFV8_7-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_8-DATARKIGS4THFV8, DATARKIGS4THFV8_9-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_A-DATARKIGS4THFV8, DATARKIGS4THFV8_B-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_C-DATARKIGS4THFV8, DATARKIGS4THFV8_D-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_E-DATARKIGS4THFV8, DATARKIGS4THFV8_F-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_10-DATARKIGS4THFV8, DATARKIGS4THFV8_11-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_12-DATARKIGS4THFV8, DATARKIGS4THFV8_13-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_14-DATARKIGS4THFV8, DATARKIGS4THFV8_15-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_16-DATARKIGS4THFV8, DATARKIGS4THFV8_17-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_18-DATARKIGS4THFV8, DATARKIGS4THFV8_19-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_1A-DATARKIGS4THFV8, DATARKIGS4THFV8_1B-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_1C-DATARKIGS4THFV8, DATARKIGS4THFV8_1D-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_1E-DATARKIGS4THFV8, DATARKIGS4THFV8_1F-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_20-DATARKIGS4THFV8, DATARKIGS4THFV8_21-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_22-DATARKIGS4THFV8, DATARKIGS4THFV8_23-DATARKIGS4THFV8
	dc.w DATARKIGS4THFV8_24-DATARKIGS4THFV8, DATARKIGS4THFV8_25-DATARKIGS4THFV8
DATARKIGS4THFV8_1: dc.b $0, $12
	dc.b $A8, $0, $1, $7, $FF, $D8
	dc.b $A8, $C, $1, $8, $FF, $E0
	dc.b $A8, $C, $1, $8, $0, $0
	dc.b $A8, $0, $9, $7, $0, $20
	dc.b $B0, $3, $1, $C, $FF, $D8
	dc.b $D0, $3, $1, $C, $FF, $D8
	dc.b $F0, $3, $1, $C, $FF, $D8
	dc.b $10, $3, $1, $C, $FF, $D8
	dc.b $30, $3, $1, $C, $FF, $D8
	dc.b $B0, $3, $9, $C, $0, $20
	dc.b $D0, $3, $9, $C, $0, $20
	dc.b $F0, $3, $9, $C, $0, $20
	dc.b $10, $3, $9, $C, $0, $20
	dc.b $30, $3, $9, $C, $0, $20
	dc.b $50, $1, $1, $10, $FF, $D8
	dc.b $50, $D, $1, $12, $FF, $E0
	dc.b $50, $D, $1, $12, $0, $0
	dc.b $50, $1, $9, $10, $0, $20
DATARKIGS4THFV8_2: dc.b $0, $E
	dc.b $A6, $0, $0, $F9, $FF, $D8
	dc.b $A6, $C, $0, $FA, $FF, $E0
	dc.b $A6, $C, $0, $FA, $0, $0
	dc.b $A6, $0, $8, $F9, $0, $20
	dc.b $AE, $3, $0, $FE, $FF, $D8
	dc.b $CE, $3, $0, $FE, $FF, $D8
	dc.b $EE, $0, $0, $FE, $FF, $D8
	dc.b $AE, $3, $0, $FE, $0, $20
	dc.b $CE, $3, $0, $FE, $0, $20
	dc.b $EE, $0, $0, $FE, $0, $20
	dc.b $F6, $0, $1, $2, $FF, $D8
	dc.b $F6, $C, $1, $3, $FF, $E0
	dc.b $F6, $C, $1, $3, $0, $0
	dc.b $F6, $0, $9, $2, $0, $20
DATARKIGS4THFV8_3: dc.b $0, $4
	dc.b $F4, $E, $20, $42, $FF, $C8
	dc.b $F4, $E, $20, $4E, $FF, $E8
	dc.b $F4, $E, $20, $5A, $0, $8
	dc.b $F4, $6, $20, $66, $0, $28
DATARKIGS4THFV8_4: dc.b $0, $6
	dc.b $D8, $E, $28, $6C, $FF, $E8
	dc.b $F0, $9, $28, $78, $FF, $F0
	dc.b $D6, $0, $28, $7E, $0, $0
	dc.b $DE, $D, $28, $7F, $FF, $F8
	dc.b $EE, $D, $28, $87, $0, $0
	dc.b $F6, $0, $28, $8F, $FF, $F8
DATARKIGS4THFV8_5: dc.b $0, $2
	dc.b $D8, $E, $28, $6C, $FF, $EE
	dc.b $F0, $9, $28, $78, $FF, $F6
DATARKIGS4THFV8_6: dc.b $0, $4
	dc.b $D8, $0, $20, $7E, $FF, $FF
	dc.b $E0, $D, $20, $7F, $FF, $EF
	dc.b $F0, $D, $20, $87, $FF, $E7
	dc.b $F8, $0, $20, $8F, $0, $7
DATARKIGS4THFV8_7: dc.b $0, $3
	dc.b $D8, $E, $28, $90, $FF, $F3
	dc.b $F0, $8, $28, $9C, $FF, $F3
	dc.b $F8, $C, $28, $9F, $FF, $F3
DATARKIGS4THFV8_8: dc.b $0, $2
	dc.b $B8, $E, $20, $A3, $FF, $E4
	dc.b $B8, $2, $20, $AF, $0, $4
DATARKIGS4THFV8_9: dc.b $0, $1
	dc.b $B8, $A, $20, $B2, $FF, $EC
DATARKIGS4THFV8_A: dc.b $0, $1
	dc.b $B8, $2, $20, $BB, $FF, $F4
DATARKIGS4THFV8_B: dc.b $0, $1
	dc.b $B8, $A, $20, $B2, $FF, $EC
DATARKIGS4THFV8_C: dc.b $0, $2
	dc.b $B8, $E, $20, $BE, $FF, $E4
	dc.b $B8, $2, $20, $CA, $0, $4
DATARKIGS4THFV8_D: dc.b $0, $3
	dc.b $D0, $F, $20, $CD, $FF, $EC
	dc.b $D8, $2, $20, $DD, $0, $C
	dc.b $F0, $9, $20, $E0, $FF, $F4
DATARKIGS4THFV8_E: dc.b $0, $3
	dc.b $D0, $F, $20, $E6, $FF, $EC
	dc.b $D8, $2, $20, $F6, $0, $C
	dc.b $F0, $9, $20, $E0, $FF, $F4
DATARKIGS4THFV8_F: dc.b $0, $2
	dc.b $C6, $5, $1, $1E, $FF, $F8
	dc.b $2, $5, $11, $1E, $FF, $F8
DATARKIGS4THFV8_10: dc.b $0, $1
	dc.b $CE, $0, $C1, $22, $FF, $FC
DATARKIGS4THFV8_11: dc.b $0, $1
	dc.b $D8, $0, $41, $23, $FF, $E8
DATARKIGS4THFV8_12: dc.b $0, $1
	dc.b $D8, $0, $41, $24, $0, $10
DATARKIGS4THFV8_13: dc.b $0, $1
	dc.b $EE, $0, $41, $25, $FF, $E3
DATARKIGS4THFV8_14: dc.b $0, $1
	dc.b $EE, $0, $41, $26, $0, $15
DATARKIGS4THFV8_15: dc.b $0, $1
	dc.b $FF, $0, $41, $27, $FF, $F1
DATARKIGS4THFV8_16: dc.b $0, $1
	dc.b $FF, $0, $41, $28, $0, $7
DATARKIGS4THFV8_17: dc.b $0, $6
	dc.b $88, $F, $63, $1B, $FF, $D8
	dc.b $88, $F, $63, $2B, $FF, $F8
	dc.b $88, $7, $63, $3B, $0, $18
	dc.b $A8, $E, $63, $43, $FF, $D8
	dc.b $A8, $E, $63, $4F, $FF, $F8
	dc.b $A8, $6, $63, $5B, $0, $18
DATARKIGS4THFV8_18: dc.b $0, $6
	dc.b $88, $F, $61, $29, $FF, $D8
	dc.b $88, $F, $61, $39, $FF, $F8
	dc.b $88, $7, $61, $49, $0, $18
	dc.b $A8, $E, $61, $51, $FF, $D8
	dc.b $A8, $E, $61, $5D, $FF, $F8
	dc.b $A8, $6, $61, $69, $0, $18
DATARKIGS4THFV8_19: dc.b $0, $6
	dc.b $88, $F, $61, $6F, $FF, $D8
	dc.b $88, $F, $61, $7F, $FF, $F8
	dc.b $88, $7, $61, $8F, $0, $18
	dc.b $A8, $E, $61, $97, $FF, $D8
	dc.b $A8, $E, $61, $A3, $FF, $F8
	dc.b $A8, $6, $61, $AF, $0, $18
DATARKIGS4THFV8_1A: dc.b $0, $2
	dc.b $88, $5, $1, $1E, $FF, $F8
	dc.b $C0, $5, $11, $1E, $FF, $F8
DATARKIGS4THFV8_1B: dc.b $0, $6
	dc.b $88, $F, $61, $B5, $FF, $D8
	dc.b $88, $F, $61, $C5, $FF, $F8
	dc.b $88, $7, $61, $D5, $0, $18
	dc.b $A8, $E, $61, $DD, $FF, $D8
	dc.b $A8, $E, $61, $E9, $FF, $F8
	dc.b $A8, $6, $61, $F5, $0, $18
DATARKIGS4THFV8_1C: dc.b $0, $1
	dc.b $CE, $5, $C2, $2F, $FF, $F8
DATARKIGS4THFV8_1D: dc.b $0, $1
	dc.b $D8, $5, $42, $33, $FF, $E4
DATARKIGS4THFV8_1E: dc.b $0, $1
	dc.b $D8, $5, $42, $37, $0, $C
DATARKIGS4THFV8_1F: dc.b $0, $1
	dc.b $EE, $5, $42, $3B, $FF, $DF
DATARKIGS4THFV8_20: dc.b $0, $1
	dc.b $EE, $5, $42, $3F, $0, $11
DATARKIGS4THFV8_21: dc.b $0, $1
	dc.b $FF, $5, $C2, $43, $FF, $ED
DATARKIGS4THFV8_22: dc.b $0, $1
	dc.b $FF, $5, $C2, $47, $0, $3
DATARKIGS4THFV8_23: dc.b $0, $6
	dc.b $88, $F, $62, $7D, $FF, $D8
	dc.b $A8, $E, $62, $8D, $FF, $D8
	dc.b $88, $F, $62, $99, $FF, $F8
	dc.b $A8, $E, $62, $A9, $FF, $F8
	dc.b $88, $7, $62, $B5, $0, $18
	dc.b $A8, $6, $62, $BD, $0, $18
DATARKIGS4THFV8_24: dc.b $0, $14
	dc.b $A6, $C, $0, $F9, $FF, $A4
	dc.b $A6, $C, $0, $FA, $FF, $C4
	dc.b $A6, $C, $0, $FA, $FF, $E4
	dc.b $A6, $C, $0, $FA, $0, $4
	dc.b $A6, $C, $0, $FA, $0, $24
	dc.b $A6, $8, $8, $F9, $0, $44
	dc.b $E, $3, $0, $FF, $FF, $A4
	dc.b $26, $C, $1, $3, $FF, $AC
	dc.b $26, $C, $1, $3, $FF, $CC
	dc.b $26, $C, $1, $3, $FF, $EC
	dc.b $26, $C, $1, $3, $0, $C
	dc.b $26, $C, $1, $3, $0, $2C
	dc.b $E, $3, $8, $FF, $0, $54
	dc.b $26, $0, $1, $3, $0, $4C
	dc.b $AE, $3, $0, $FE, $FF, $A4
	dc.b $CE, $3, $0, $FE, $FF, $A4
	dc.b $EE, $3, $0, $FE, $FF, $A4
	dc.b $AE, $3, $0, $FE, $0, $54
	dc.b $CE, $3, $0, $FE, $0, $54
	dc.b $EE, $3, $0, $FE, $0, $54
DATARKIGS4THFV8_25: dc.b $0, $1
	dc.b $0, $0, $0, $A3, $0, $0
	even